# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"

  # Changer le hostname pour chaque machine
  config.vm.hostname = "master"
  #config.vm.hostname = "worker1"
  #config.vm.hostname = "worker2"

  # Penser à modifier l'ip pour chaque machine

  # master
  config.vm.network "private_network", ip: "192.168.33.10"

  # workers
  #config.vm.network "private_network", ip: "192.168.33.11"
  #config.vm.network "private_network", ip: "192.168.33.12"

  # 2GB de RAM minimum
  config.vm.provider "virtualbox" do |vb|
     vb.memory = "2048"
   end
end
